# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [maury, trump]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username hunters.io
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.bookatable.co.uk','https://covid19.apple.com','https://cdc.gov','https://vodoo.io','https://marchofdimes.org','https://knightline.com','https://mycreed.io','https://eBay.com','https://bigo.com']
